Fix a bug that executing `setup.py` failed for NameError.
